version: "3.7"

services:
  dockerizeExpressApp:
    build:
      args:
        user: developer
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: express-app-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh
    ports:
    - "5000:5000"
    networks:
      - dockerizeExpress
  
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_ALLOW_EMPTY_PASSWORD=yes  # set when you don't want set password for root user
      MYSQL_ROOT_PASSWORD: root123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-config/mysql:/var/lib/mysql
    networks:
      - dockerizeExpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    ports:
        - 8080:80
    links:
        - db
    restart: unless-stopped
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    networks:
        - dockerizeExpress

networks:
  dockerizeExpress:
    driver: bridge