version: "3.7"

services:
  dockerNodeApp:
    build:
      args:
        user: developer
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: docker-node-container
    restart: unless-stopped
    # environment:
      # VIRTUAL_HOST: laravel.test
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh
    expose:
      - "5000"
    ports:
    - "5000:5000"
    environment:
      - NODE_PORT=5000
    networks:
      - nodeDocker
  
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_ALLOW_EMPTY_PASSWORD=yes  # set when you don't want set password for root user
      MYSQL_ROOT_PASSWORD: root123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-config/mysql:/var/lib/mysql
    networks:
      - nodeDocker

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d
      - ./docker-config/nginx/ssl:/etc/nginx/conf.d/ssl
      - ./docker-config/nginx/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf
    networks:
      - nodeDocker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    ports:
        - 8080:80
    links:
        - db
    restart: unless-stopped
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    networks:
        - nodeDocker

networks:
  nodeDocker:
    driver: bridge